.TH "includes/G-2301-03-P1-types.h" 3 "Fri Apr 25 2014" "Version 2.0" "IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2301-03-P1-types.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOK\fP   0"
.br
.ti -1c
.RI "#define \fBERROR\fP   -1 /*Generic error*/"
.br
.ti -1c
.RI "#define \fBERROR_Q_LENGTH\fP   -2 /*Invalid queue length for a TCP connection*/"
.br
.in -1c
.SH "Detailed Description"
.PP 
Types predefined\&. 
.PP
\fBAuthor:\fP
.RS 4
Enrique Cabrerizo Fernandez and Guillermo Ruiz Alvarez
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IRC from the source code\&.
